insert into `oml__type` (`id`, `name`, `column`, `inputId`) values
(1, "TYPE", "typeId", 4),
(2, "LABEL", "text", 1),
(3, "TEXT", "text", 2),
(4, "PASSWORD", "text", 6),
(5, "BOOLEAN", "number", 5),
(6, "NUMBER", "number", 3),
(7, "MONEY", "text", 8),
(8, "DATE", "timestamp", 9),
(9, "DURATION", "text", 10),
(10, "IMAGE", "NOT IMPLEMENTED", 4),
(11, "IMAGE_VALUE", "mediaId", 7),
(12, "ENUMERATOR", "NOT IMPLEMENTED", 4),
(13, "ENUMERATOR_VALUE", "enumeratorItemId", 4),
(14, "QUANTITY", "NOT IMPLEMENTED", 4),
(15, "QUANTITY_VALUE", "quantityItemId", 4),
(16, "DATASHEET", "datasheetId", 4);